# ResistanceKill v1.0 by AntTheAntster
# Made to request on the Bukkit Plugin Requests Forum
# Any questions or issues, message me on Discord: AntTheAntster

# Duration of resistance (in seconds)
Duration: 60

# Max reachable level
Max Level: 3